spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jaehodb.cmokv5cfhdtd.us-east-2.rds.amazonaws.com:3306/portfolio?serverTimezone=UTC
    username: portfolio
    password: portfolio
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

